pull_request_template:
  - name: \[L0\] 리뷰 불가
    path: .github/PULL_REQUEST_TEMPLATE/L0_Review_Impossible.md
  - name: \[L1\] 필수 변경 요청
    path: .github/PULL_REQUEST_TEMPLATE/L1_Change_Required.md
  - name: \[L2\] 변경 협의 필요
    path: .github/PULL_REQUEST_TEMPLATE/L2_Change_Discussion.md
  - name: \[L3\] 중요 질문
    path: .github/PULL_REQUEST_TEMPLATE/L3_Important_Question.md
  - name: \[L4\] 변경 제안
    path: .github/PULL_REQUEST_TEMPLATE/L4_Change_Suggestion.md
  - name: \[L5\] 참고 의견
    path: .github/PULL_REQUEST_TEMPLATE/L5_Reference_Opinion.md